<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Async await(Chai aur Code)</title>
  </head>
  <body style="background-color: black; color: aliceblue">
    <h1>async await (By chai aur code)</h1>

    <script>
      /******  Example.1  ******/
      // const promiseOne = new Promise((reslove, reject)=>{
      //   setTimeout(()=>{
      //     if (true) {
      //       reslove({ userName: "JavaScripts", password: "12345" });
      //     } else {
      //       reject("Error: Something went wrong");
      //     }
      //   }, 1000);
      // });

      // async function consumePromiseOne() {
      //   let result = await promiseOne;
      //   console.log(result);
      //   // console.log(await promiseOne);  //
      // }
      // consumePromiseOne();

      /* Notes:
          async await me condition true ho gaya tab toh execute ho jaega agar condition false
          ho gaya toh dikkat hai esliye always use try catch method.
          async await me try aur catch method  use hota hai=>  agar condtion true huwa tab promise 
          resolve kr dega agar condition false huwa toh error catch kreaga.
      */

      /******  Example.2  ******/
      // const promiseTwo = new Promise(function (reslove, reject) {
      // setTimeout(function () {
      //     if (false) {
      //       reslove({ userName: "JavaScripts", password: "12345" });
      //     } else {
      //       reject("Error: Something went wrong");
      //     }
      //   }, 1000);
      // });

      // async function myPromise (){
      //   try {
      //       let result = await promiseTwo      //kisi varibale me store kr lete hai like result.
      //       console.log(result);
      //   } catch (error) {
      //       console.log(error);
      //   }
      // }
      // myPromise ()

      /* Notes: async await me try aur catch use hota hai=>  agar condtion true huwa tab promise 
         resolve kr dega agar condition false huwa toh error catch kreaga.*/

      /******  Example.3  ******/
      //  const bookTicket = new Promise((reslove, reject)=>{
      //     let confirm = true
      //     if(false){
      //       reslove('Your ticket is Confirmed')
      //     }else{
      //       reject('Your ticket is Cancelled ')
      //     }
      //  });

      //  async function myBooking (){
      //   try {
      //       const result = await bookTicket
      //       console.log(result);
      //   } catch (error) {
      //       console.log(error);
      //   }
      //  }
      //  myBooking()

      //Example.4
      // async function getAllUsers() {
      //   try {
      //      const response = await fetch("https://jsonplaceholder.typicode.com/users");
      //      let data = response.json();
      //      console.log(data);
      //   } catch (error) {
      //     console.log(error);
      //   }
      // }
      // getAllUsers();
    </script>
  </body>
</html>
